#pragma once
// DippInn boot logo for Game Boy Color (GBDK-2020), ~8 s. Self-contained: needs only this .h, dippinn_logo.c and
// dippinn_logo_data.c (generated by tools/make_dippinn_logo.py).
//
//   dippinn_logo_play();   // call first thing in main(); blocks until done (START skips it)
//
// It takes over BG, sprites, the palettes, then hands the machine back: LCD off, interrupts
// as they were (VBlank only), LCDC = BG on / 0x8000 tile data, all other registers untouched. Your own init
// (tiles, palettes, SPRITES_8x8, DISPLAY_ON ...) just runs afterwards as if the logo had never been there.
void dippinn_logo_play(void);
