// EMPIRE-ANTS - ant-colony terraforming strategy for Game Boy Color (GBDK-2020)
// 32x32 scrolling world, queen ants, sound. All graphics generated in code.
#include <gb/gb.h>
#include <gb/cgb.h>
#include <stdint.h>
#include <rand.h>
#include "dippinn_logo.h"
#include "art.h"            // BGT, SPT, TAT: tile data generated by tools/make_art.py

#define W 32            // world size = size of the hardware BG map
#define H 32
#define VW 20           // visible world tiles (bottom 2 rows are the HUD window)
#define VH 16
#define MAXA 100        // ant slots: 50 per colony (more than the 40 hardware sprites, so only ants in view get a sprite)
#define NSPR 37         // hardware sprites 0..36 show the ants on screen; 37, 38 = queens, 39 = cursor
#define QSPR 37
#define MANA_MAX 20     // mana cap
#define MANA_PER_FOOD 1 // tribute: mana per food a black ant carries home
#define OFFER_FOOD 2    // embezzle (SELECT+A): food spent ...
#define OFFER_MANA 4    // ... for this much mana
#define BT 128          // first terrain tile
#define BAR_F 134       // mana bar tiles (free slots after the 6 terrain tiles)
#define BAR_E 135
#define TT 176          // first title-logo tile (13 tiles of 3D lettering)
#define FT 136          // first font tile (40 glyphs)
#define TS 189          // first title-scenery tile (12 tiles: stars, moon, hills, grass, soil)
#define AR 201          // tiles for the < > arrows of the level picker (2 tiles)
#define TW 3            // first walking-ant sprite tile (2 frames) used on the title screen

typedef struct { uint8_t x, y, team, alive, carry, sol; } Ant;

static uint8_t hgt[H][W], food[H][W], ph[H][W];
static Ant ant[MAXA];
static uint8_t nestx[2], nesty[2], stock[2], qhp[2], ncnt[2], hatched[2];
static uint8_t cx, cy, mana, tk, over, camx, camy, sandbox, cheat, ff, appr;       // appr = popularity 0-99
static uint16_t etk;                           // ticks since the last election
static const char *msg; static uint8_t msgt;      // short HUD hint (replaces the QUEEN row for ~1.5 s)
static int16_t scx, scy;                       // pixel scroll
static uint16_t seed;
static uint8_t norec, slotgame, hassave, loadreq; // norec: this game does not count for records; slotgame: the save slot holds this game;
                                               // hassave: valid save in cartridge RAM; loadreq: the title asked to continue it
static uint16_t gt;                            // game time in ticks (7.5 per second; pause and ant eye do not count)
static uint8_t tut, tev, tutor, lcx, lcy;      // tutorial: lesson (0 = off), events the player did, from-title flag, last cursor
// Cheat code (in play): infinite mana + food. Ends on A, so it never collides with START (pause).
static const uint8_t CHEAT[10] = {J_LEFT, J_LEFT, J_RIGHT, J_RIGHT, J_UP, J_DOWN, J_UP, J_DOWN, J_B, J_A};
static const int8_t DX[4] = {1, -1, 0, 0};
static const int8_t DY[4] = {0, 0, 1, -1};

// ---------- difficulty ----------
// 0 EASY, 1 NORMAL, 2 HARD (title screen: LEFT/RIGHT). Everything that differs lives in this table and set_rules() copies it into the
// variables the game loop reads. NORMAL is exactly the game as it was before levels existed.
typedef struct { uint8_t mana0, trk, drn, hc, thr, q0, q1; } Rules;
static const Rules DIF[3] = {
  // start MP | mana trickle mask | popularity drain mask | red food per ant | red soldiers march at | my queen HP | red queen HP
  { 14, 15, 63, 4, 12, 7, 4 },
  { 10, 31, 31, 3,  8, 5, 5 },
  {  6, 63, 15, 2,  6, 4, 6 }};
static const char *const DNAME[3] = {"EASY  ", "NORMAL", "HARD  "};
static uint8_t diff, gdiff;                    // diff = the title screen's choice (remembered); gdiff = level of the game being played
static uint8_t trk, drn, hcost[2], thr[2], qmax[2];
static void set_rules(uint8_t d) {
  trk = DIF[d].trk; drn = DIF[d].drn;          // mana +1 every (trk+1) ticks, popularity -1 every (drn+1) ticks
  hcost[0] = 3; hcost[1] = DIF[d].hc;          // food per hatched ant
  thr[0] = 8;   thr[1] = DIF[d].thr;           // colony size at which soldiers start marching
  qmax[0] = DIF[d].q0; qmax[1] = DIF[d].q1;    // queen HP
}

// ---------- palettes & graphics (generated from strings) ----------
static const palette_color_t bpal[24] = {
  RGB(8,16,28), RGB(28,24,14), RGB(8,20,6), RGB(6,4,3),      // 0: terrain
  RGB(0,0,0),   RGB(8,8,8),    RGB(20,20,20), RGB(31,31,31), // 1: HUD text
  RGB(0,0,0),   RGB(10,5,1),   RGB(22,12,3),  RGB(31,27,8),   // 2: (spare)
  RGB(3,7,20),   RGB(11,26,9),  RGB(4,16,6),    RGB(21,14,6),    // 3: ant eye, land + rock
  RGB(3,7,20),   RGB(8,18,30),  RGB(11,26,9),   RGB(4,16,6),     // 4: ant eye, water
  RGB(3,7,20),   RGB(31,6,4),   RGB(0,0,0),     RGB(4,16,6)};    // 5: ant eye, red / black ants
// title screen palettes (replace bpal while the title is up): night sky in three bands, gold logo + two shine steps, hills
static const palette_color_t tpal[32] = {
  RGB(1,1,5),   RGB(5,5,13),   RGB(11,11,22), RGB(31,29,22),   // 0: night sky (top)
  RGB(4,2,9),   RGB(9,6,17),   RGB(15,10,23), RGB(31,29,22),   // 1: dusk sky
  RGB(10,4,11), RGB(17,8,15),  RGB(24,13,15), RGB(31,29,22),   // 2: horizon glow
  RGB(1,1,5),   RGB(10,5,1),   RGB(22,12,3),  RGB(31,27,8),    // 3: gold logo
  RGB(10,4,11), RGB(13,26,8),  RGB(5,15,7),   RGB(9,5,4),      // 4: hills, grass, soil
  RGB(1,1,5),   RGB(5,5,13),   RGB(11,11,22), RGB(31,29,22),   // 5: spare
  RGB(1,1,5),   RGB(14,8,2),   RGB(28,18,6),  RGB(31,31,16),   // 6: logo shine, soft
  RGB(1,1,5),   RGB(20,14,6),  RGB(31,26,14), RGB(31,31,28)};  // 7: logo shine, bright
static const palette_color_t spal[12] = {
  RGB(0,0,0), RGB(2,2,2),   RGB(14,14,14), RGB(31,31,31),
  RGB(0,0,0), RGB(26,3,3),  RGB(31,12,8),  RGB(31,31,31),
  RGB(0,0,0), RGB(31,31,0), RGB(31,20,0),  RGB(31,31,31)};

// terrain / mana-bar / sprite / scenery tiles live in art.h (BGT: 0 water,1 sand,2 grass,3 hill,4 nest,5 food, 6-7 mana bar;
// SPT: 0 worker ant, 1 cursor, 2 queen, 3-4 walking ant; TAT: title scenery)

// ---------- title scenery map (tiles TS..TS+11 from TAT) ----------
static const char SCKEY[] = ".*,abcd=/\\H#";            // SCN character -> tile TS + index (space = blank font tile)
static const char *const SCN[18] = {
  " .    *    ,  .     ",
  "  ,      .      ab  ",
  "            *   cd .",
  ".               ,   ",
  " *                . ",
  "   .    ,   .    *  ",
  "                    ",
  " . ,     .     *    ",
  ".    ,     .      * ",
  " .               ,  ",
  "   .    ,     .     ",
  "                   .",
  "                  , ",
  "               /\\   ",
  "   /\\         /HH\\  ",
  "  /HH\\   /\\  /HHHH\\ ",
  "====================",
  "####################"};

// 3x5 font, one octal digit per row (4=left px, 2=middle, 1=right)
// order: space, 0-9, A-Z, ':', '!', '/'
static const uint16_t FONT[40] = {
  0,
  075557,026227,071747,071717,055711,074717,074757,071122,075757,075717,
  025755,065656,034443,065556,074647,074644,034553,055755,072227,011152,
  055655,044447,057755,065555,025552,065644,025563,065655,034216,072222,
  055557,055552,055775,055255,055222,071247,
  002020,022202,011244};

static void mk_glyph(uint8_t *d, uint16_t g) {
  uint8_t y, lo;
  for (y = 0; y < 8; y++) {
    lo = (y >= 1 && y <= 5) ? (uint8_t)(((g >> (3 * (5 - y))) & 7) << 3) : 0;
    d[y * 2] = lo; d[y * 2 + 1] = lo;          // both planes = colour 3
  }
}

// ---------- text on the window layer ----------
static uint8_t gi(char c) {
  if (c >= '0' && c <= '9') return 1 + (c - '0');
  if (c >= 'A' && c <= 'Z') return 11 + (c - 'A');
  if (c == ':') return 37;
  if (c == '!') return 38;
  if (c == '/') return 39;
  return 0;
}
static void put_char(uint8_t x, uint8_t y, char c) { set_win_tile_xy(x, y, c == '<' ? AR : c == '>' ? AR + 1 : FT + gi(c)); }
static void put_str(uint8_t x, uint8_t y, const char *s) { while (*s) put_char(x++, y, *s++); }
static void put_num(uint8_t x, uint8_t y, uint8_t n) {      // right-aligned, no leading zero
  if (n > 99) n = 99;
  put_char(x, y, n > 9 ? '0' + n / 10 : ' '); put_char(x + 1, y, '0' + n % 10);
}
static void put_dec(uint8_t x, uint8_t y, uint16_t n, uint8_t w) {   // right-aligned in w columns
  uint8_t i;
  for (i = w; i--; ) { put_char(x + i, y, (n || i == w - 1) ? (char)('0' + n % 10) : ' '); n /= 10; }
}
static void put_time(uint8_t x, uint8_t y, uint16_t s) {             // MM:SS (5 columns), or NONE for no record yet
  uint8_t m, r;
  if (!s) { put_str(x, y, "NONE "); return; }
  m = (uint8_t)(s / 60); if (m > 99) m = 99; r = (uint8_t)(s % 60);
  put_char(x, y, m > 9 ? '0' + m / 10 : ' '); put_char(x + 1, y, '0' + m % 10); put_char(x + 2, y, ':');
  put_char(x + 3, y, '0' + r / 10); put_char(x + 4, y, '0' + r % 10);
}
static void attr(uint8_t x, uint8_t y, uint8_t n, uint8_t p) {   // set the palette of n window cells (palette 1 = white text, 2 = gold)
  VBK_REG = VBK_ATTRIBUTES;
  while (n--) set_win_tile_xy(x++, y, p);
  VBK_REG = VBK_TILES;
}
static const char *put_line(uint8_t y, const char *s) {          // one '\n'-terminated line, padded to 20 columns; returns the next line
  uint8_t x = 0;
  while (*s && *s != '\n') put_char(x++, y, *s++);
  while (x < 20) put_char(x++, y, ' ');
  return *s ? s + 1 : s;
}
// ---------- 3D "perspective" title lettering: EmpIre-antS ----------
// 3x5 font glyphs stretched 2x wide, extruded 2 px down-right in two darker shades (gold -> brown -> dark);
// the first E and last S are double height so the word reads Empire-antS with towering end caps.
static uint8_t cv[16][8];
static void mk_3d(uint8_t *d, uint16_t g, uint8_t tall, uint8_t part) {
  uint8_t gx, gy, k, x, y, r, c, v, lo, hi, sy = tall ? 2 : 1, y0 = tall ? 3 : 8;
  for (r = 0; r < 16; r++) for (c = 0; c < 8; c++) cv[r][c] = 0;
  for (k = 3; k--; )                                    // extrusion layers 2, 1 then front face 0 (back to front)
    for (gy = 0; gy < 5; gy++) for (gx = 0; gx < 3; gx++)
      if ((g >> (3 * (4 - gy))) & (4 >> gx))
        for (y = 0; y < sy; y++) for (x = 0; x < 2; x++) cv[y0 + gy * sy + y + k][gx * 2 + x + k] = 3 - k;
  for (r = 0; r < 8; r++) {
    lo = hi = 0;
    for (c = 0; c < 8; c++) { v = cv[part * 8 + r][c]; lo = (lo << 1) | (v & 1); hi = (hi << 1) | (v >> 1); }
    d[r * 2] = lo; d[r * 2 + 1] = hi;
  }
}
static void title_tiles(uint8_t *b) {                   // 13 tiles: E top/bottom, S top/bottom, then M P I R E - A N T
  static const char SM[10] = "MPIRE-ANT";
  uint8_t i;
  mk_3d(b,      FONT[gi('E')], 1, 0); mk_3d(b + 16, FONT[gi('E')], 1, 1);
  mk_3d(b + 32, FONT[gi('S')], 1, 0); mk_3d(b + 48, FONT[gi('S')], 1, 1);
  for (i = 0; i < 9; i++) mk_3d(b + (4 + i) * 16, SM[i] == '-' ? 0700 : FONT[gi(SM[i])], 0, 1);
}
static void logo_cells(uint8_t x0, uint8_t y0, uint8_t pal) {
  uint8_t i;
  VBK_REG = VBK_ATTRIBUTES;
  for (i = 0; i < 11; i++) { set_win_tile_xy(x0 + i, y0, pal); set_win_tile_xy(x0 + i, y0 + 1, pal); }
  VBK_REG = VBK_TILES;
}
static void title_logo(uint8_t x0, uint8_t y0) {
  static const uint8_t R2[11] = {1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 3};   // bottom row: E, M P I R E - A N T, S
  uint8_t i;
  for (i = 0; i < 11; i++) { set_win_tile_xy(x0 + i, y0, FT); set_win_tile_xy(x0 + i, y0 + 1, TT + R2[i]); }
  set_win_tile_xy(x0, y0, TT); set_win_tile_xy(x0 + 10, y0, TT + 2);
  logo_cells(x0, y0, 3);                                // gold palette (title set)
}

// ---------- pause / help: a scrolling text list on window rows 3-15 (UP/DOWN scrolls); '#' marks a gold heading ----------
#define HR 13                                      // help lines visible at once
static const char HELP[] =
  "#CONTROLS\n"
  "A      RAISE LAND\n"
  "B      LOWER LAND\n"
  "SEL    FLOOD 3X3 8MP\n"
  "SEL A  EMBEZZLE\n"
  "SEL B  FAST FORWARD\n"
  "SEL START  ANT EYE\n"
  "START  PAUSE:RESUME\n"
  "PAUSED A  SAVE GAME\n"
  "PAUSED B  QUIT\n"
  "\n"
  "#GOAL\n"
  "KILL THE RED QUEEN\n"
  "BEFORE THEY KILL\n"
  "YOURS\n"
  "\n"
  "#MANA\n"
  "EDITS COST 1 MP\n"
  "FLOOD COSTS 8 MP\n"
  "REFILLS FROM TRICKLE\n"
  "FOOD CARRIED HOME\n"
  "AND ELECTION AID\n"
  "SEL A SWAPS 2 FOOD\n"
  "FOR 4 MP: P DOWN 5\n"
  "\n"
  "#HUD\n"
  "MP    MANA AND BAR\n"
  "F     YOUR FOOD\n"
  "Q     QUEEN HP\n"
  "      YOURS/RED\n"
  "A     YOUR ANTS\n"
  "R     RED ANTS\n"
  "P     POPULARITY\n"
  "FF    FAST FORWARD\n"
  "\n"
  "#ELECTIONS\n"
  "EVERY MINUTE:\n"
  "P 50 UP  8 MP AID\n"
  "P 25 TO 49  NOTHING\n"
  "P UNDER 25  COUP:\n"
  "FOOD HALVED MP LOST\n"
  "\n"
  "#ANTS\n"
  "THEY FOLLOW TRAILS\n"
  "BUILD EASY PATHS\n"
  "3 FOOD HATCH AN ANT\n"
  "SOLDIERS ATTACK AT 8\n"
  "\n"
  "#LEVELS\n"
  "L R ON TITLE PICKS\n"
  "EASY: MORE MP AND\n"
  "SLOWER P LOSS: RED\n"
  "HATCHES SLOWER\n"
  "HARD: LESS MP AND\n"
  "FASTER P LOSS: RED\n"
  "HATCHES FASTER AND\n"
  "ATTACKS EARLY\n";
static uint8_t htop, hlines;                       // first visible line, total lines
static uint16_t hdp;                               // which visible rows currently have the gold palette
static void help_draw(void) {
  const char *s = HELP; uint8_t n = 0, r; uint16_t hd = 0;
  while (*s) {
    if (n >= htop && n < htop + HR) {
      r = n - htop;
      if (*s == '#') { s++; hd |= (uint16_t)1 << r; }
      s = put_line(3 + r, s);
    } else while (*s++ != '\n');
    n++;
  }
  hlines = n;
  for (r = 0; r < HR; r++) if (((hd ^ hdp) >> r) & 1) attr(0, 3 + r, 20, ((hd >> r) & 1) ? 2 : 1);
  hdp = hd;
  put_num(15, 2, htop + HR); put_char(17, 2, '/'); put_num(18, 2, n);      // last visible line / total
}
static void help_open(void) {
  htop = 0;
  put_str(0, 2, "PAUSED"); attr(0, 2, 6, 2); put_str(7, 2, DNAME[gdiff]);
  put_line(16, "A:SAVE  B:QUIT");
  put_str(0, 17, "U/D SCROLL  START:GO");
  help_draw();
}
static void help_scroll(int8_t d) {
  uint8_t t = htop;
  if (d < 0) { if (t) t--; } else if (t + HR < hlines) t++;
  if (t != htop) { htop = t; help_draw(); }
}
static void win_clear(void) {                      // blank text, white palette everywhere
  uint8_t x, y;
  for (y = 0; y < 18; y++) for (x = 0; x < 20; x++) set_win_tile_xy(x, y, FT);
  for (y = 0; y < 18; y++) attr(0, y, 20, 1);
  hdp = 0;
}
static void say(const char *m) { msg = m; msgt = 12; }
static uint8_t hdirty = 1, hlab, hm = 255, hs = 255, hq0 = 255, hq1 = 255, ha = 255, hr = 255, hf = 255, hp = 255;
// HUD (window rows 0-1, labels gold, numbers white):
//   row 0   MP nn [10-cell mana bar] F nn           row 1   Q a/b   A nn   R nn   P nn   FF
// A hint (say()) temporarily replaces row 1. Window writes are slow, so only what changed is redrawn.
static void hud(void) {
  uint8_t i;
  if (hdirty) {                                  // new game: static labels + force every number
    put_str(0, 0, "MP"); attr(0, 0, 2, 2); put_char(17, 0, 'F'); attr(17, 0, 1, 2);
    hm = hs = hq0 = hq1 = ha = hr = hf = hp = 255; hlab = 0; hdirty = 0;
  }
  if (mana != hm) {
    hm = mana; put_num(3, 0, mana);
    for (i = 0; i < 10; i++) set_win_tile_xy(6 + i, 0, mana > 2 * i ? BAR_F : BAR_E);   // mana bar, 2 mana per cell
  }
  if (stock[0] != hs) { hs = stock[0]; put_num(18, 0, hs); }
  if (msgt) {                                   // hint overlay: text padded to the full 20 columns
    uint8_t x = 0; const char *m = msg;
    while (x < 20) put_char(x++, 1, *m ? *m++ : ' ');
    msgt--;
    if (hlab) { attr(0, 1, 20, 1); hlab = 0; }  // labels must be redrawn afterwards
    return;
  }
  if (!hlab) {
    for (i = 0; i < 20; i++) put_char(i, 1, ' ');
    put_char(0, 1, 'Q'); put_char(2, 1, '/'); put_char(6, 1, 'A'); put_char(10, 1, 'R'); put_char(14, 1, 'P');
    attr(0, 1, 1, 2); attr(6, 1, 1, 2); attr(10, 1, 1, 2); attr(14, 1, 1, 2);
    hq0 = hq1 = ha = hr = hp = hf = 255; hlab = 1;
  }
  if (qhp[0] != hq0) { hq0 = qhp[0]; put_char(1, 1, '0' + hq0); }
  if (qhp[1] != hq1) { hq1 = qhp[1]; put_char(3, 1, '0' + hq1); }
  if (ncnt[0] != ha) { ha = ncnt[0]; put_num(7, 1, ha); }
  if (ncnt[1] != hr) { hr = ncnt[1]; put_num(11, 1, hr); }
  if (appr != hp) { hp = appr; put_num(15, 1, hp); }
  if (ff != hf) { hf = ff; put_str(18, 1, ff ? "FF" : "  "); attr(18, 1, 2, ff ? 2 : 1); }   // FF = fast forward on
}

// ---------- sound ----------
#define N_C4 1548
#define N_G4 1714
#define N_C5 1797
#define N_E5 1849
#define N_G5 1881
#define N_C6 1923
static const uint16_t WIN_TUNE[6]  = {N_C5, N_E5, N_G5, N_C6, N_G5, N_C6};
static const uint16_t LOSE_TUNE[4] = {N_G5, N_E5, N_C5, N_C4};
static const uint16_t *tune_p;
static uint8_t jl, ji, jt;

static uint8_t h1, h2, hn;   // music yields a channel for a few frames after a sound effect uses it
// Music + jingles are driven by the VBlank interrupt (snd_isr), so tempo never depends on how long a game frame takes.
// Everything the main loop does to the sound registers / music state is wrapped in disable/enable_interrupts so the
// interrupt can never land halfway through a multi-register write.
static void ch1_raw(uint8_t sweep, uint16_t f, uint8_t env) {
  h1 = 14;
  NR10_REG = sweep; NR11_REG = 0x80; NR12_REG = env;
  NR13_REG = (uint8_t)f; NR14_REG = 0x80 | (uint8_t)(f >> 8);
}
static void ch2_raw(uint16_t f, uint8_t env) {
  h2 = 12;
  NR21_REG = 0x80; NR22_REG = env;
  NR23_REG = (uint8_t)f; NR24_REG = 0x80 | (uint8_t)(f >> 8);
}
static void ch1(uint8_t sweep, uint16_t f, uint8_t env) { disable_interrupts(); ch1_raw(sweep, f, env); enable_interrupts(); }
static void ch2(uint16_t f, uint8_t env) { disable_interrupts(); ch2_raw(f, env); enable_interrupts(); }
static void noise(uint8_t env, uint8_t poly) {
  disable_interrupts();
  hn = 16;
  NR41_REG = 0; NR42_REG = env; NR43_REG = poly; NR44_REG = 0x80;
  enable_interrupts();
}
static void sfx_raise(void) { ch1(0x15, N_C5, 0xA1); }
static void sfx_lower(void) { ch1(0x1D, N_G4, 0xA1); }
static void sfx_deny(void)  { ch1(0x00, N_C4, 0x81); }
static void sfx_mana(void)  { ch1(0x16, N_G5, 0x91); }
static void sfx_flood(void) { noise(0xA3, 0x55); }
static void sfx_food(void)  { ch2(N_E5, 0x71); }
static void sfx_spawn(void) { ch2(N_C6, 0x81); }
static void sfx_fight(void) { noise(0x81, 0x33); }
static void sfx_hit(void)   { noise(0xC2, 0x44); }
static void sfx_qdead(void) { noise(0xF7, 0x77); }
static void jingle(const uint16_t *n, uint8_t len) { disable_interrupts(); tune_p = n; ji = 0; jt = 0; jl = len; enable_interrupts(); }
static void jingle_update(void) {
  if (ji >= jl) return;
  if (jt == 0) { ch2_raw(tune_p[ji++], 0xB2); jt = 10; } else jt--;
}

// ---------- music: 4-channel loop in A minor, 112 BPM, 8 bars (~17 s) ----------
// ch1 = arpeggio, ch2 = lead, ch3 (wave) = bass, ch4 (noise) = drums. SFX borrow channels via h1/h2/hn.
#ifndef WAVERAM
#define WAVERAM ((volatile uint8_t *)0xFF30)
#endif
// pulse-channel frequency register for MIDI notes 36 (C2) .. 99; the wave channel plays one octave lower, so bass uses +12
static const uint16_t NOTE[64] = {
  44, 157, 263, 363, 457, 547, 631, 711,
  786, 856, 923, 986, 1046, 1102, 1155, 1205,
  1253, 1297, 1339, 1379, 1417, 1452, 1486, 1517,
  1547, 1575, 1602, 1627, 1650, 1673, 1694, 1714,
  1732, 1750, 1767, 1783, 1798, 1812, 1825, 1837,
  1849, 1860, 1871, 1881, 1890, 1899, 1907, 1915,
  1923, 1930, 1936, 1943, 1949, 1954, 1959, 1964,
  1969, 1974, 1978, 1982, 1985, 1989, 1992, 1995};
static const uint8_t LEAD[64] = {         // 8 bars x 8 eighth notes, 0 = rest (value = semitones above C2)
  40,0,45,0,43,40,36,0,   41,0,45,0,48,45,41,0,   40,43,40,36,38,40,43,0,   38,0,43,0,47,0,45,43,
  40,0,45,0,48,47,45,40,  41,45,48,0,45,41,40,41, 38,43,47,50,47,43,38,0,    40,44,47,0,47,44,40,0};
// chord roots as semitones above C2
static const uint8_t BROOT[8] = {9, 5, 12, 7, 9, 5, 7, 4};      // Am F C G Am F G E
static const uint8_t BPAT[8]  = {0, 0, 12, 0, 7, 0, 12, 7};     // bass pattern relative to the root
static const uint8_t ARPN[8][3] = {{21,24,28},{17,21,24},{24,28,31},{19,23,26},{21,24,28},{17,21,24},{19,23,26},{16,20,23}};
static const uint8_t ARPO[4]  = {0, 1, 2, 1};
static const uint8_t DPOLY[8] = {0x75,0x21,0x43,0x21,0x75,0x21,0x43,0x21};   // kick hat snare hat kick hat snare hat
static const uint8_t DENV[8]  = {0xA1,0x41,0x81,0x41,0xA1,0x41,0x81,0x41};
static const uint8_t WAVE[16] = {0x01,0x23,0x45,0x67,0x89,0xAB,0xCD,0xEF,0xFE,0xDC,0xBA,0x98,0x76,0x54,0x32,0x10};  // triangle
static uint8_t mus_on, mt, ms;

static void music_start(void) {
  uint8_t i;
  disable_interrupts();
  NR30_REG = 0;                                  // DAC off while loading the waveform
  for (i = 0; i < 16; i++) WAVERAM[i] = WAVE[i];
  NR30_REG = 0x80;
  mt = 7; ms = 0; mus_on = 1;                    // first step plays on the next frame
  enable_interrupts();
}
static void music_stop(void) {
  disable_interrupts();
  mus_on = 0;
  NR12_REG = 0; NR22_REG = 0; NR42_REG = 0; NR30_REG = 0;
  enable_interrupts();
}
static void music_update(void) {                 // runs from the VBlank interrupt, once per frame
  uint8_t b, e, n; uint16_t f;
  if (h1) h1--; if (h2) h2--; if (hn) hn--;
  if (!mus_on || ++mt < 8) return;               // 8 frames per 16th note
  mt = 0; b = ms >> 4;
  if (!h1) {                                     // arpeggio on every 16th
    f = NOTE[ARPN[b][ARPO[ms & 3]]];
    NR10_REG = 0; NR11_REG = 0x40; NR12_REG = 0x42; NR13_REG = (uint8_t)f; NR14_REG = 0x80 | (uint8_t)(f >> 8);
  }
  if (!(ms & 1)) {                               // everything else on eighth notes
    e = (ms & 15) >> 1;
    f = NOTE[BROOT[b] + BPAT[e] + 12];           // bass (wave channel, short length for a plucked feel)
    NR30_REG = 0x80; NR31_REG = 0xC8; NR32_REG = 0x40; NR33_REG = (uint8_t)f; NR34_REG = 0xC0 | (uint8_t)(f >> 8);
    n = LEAD[(b << 3) + e];
    if (n && !h2) {                              // lead
      f = NOTE[n];
      NR21_REG = 0x80; NR22_REG = 0x83; NR23_REG = (uint8_t)f; NR24_REG = 0x80 | (uint8_t)(f >> 8);
    }
    if (!hn) { NR41_REG = 0; NR42_REG = DENV[e]; NR43_REG = DPOLY[e]; NR44_REG = 0x80; }   // drums
  }
  ms = (ms + 1) & 127;
}


// ---------- title theme: E phrygian-dominant, ~81 BPM, 16 bars (8 + 8), in stereo ----------
// ch1 = echo of the lead (hard left), ch2 = lead with vibrato (hard right), ch3 = pulsing 3+3+2 drone bass (centre),
// ch4 = tiny footsteps that ping-pong between the speakers. The title owns all four channels (no sfx play there).
static const uint8_t TLEAD[128] = {   // one entry per eighth note: 0 = rest, 1 = hold, else semitones above C2 (like LEAD)
   0, 0, 0, 0,  0, 0,35,36,
  40, 1, 1,38, 36, 1,35,33,
  32, 1,33, 1, 35,36,35,33,
  32, 1, 1, 1,  0, 0,35,36,
  41, 1,40,38, 40, 1,36,38,
  36, 1, 1,35, 33, 1,32,33,
  44, 1,41,40, 38,36,35, 1,
  40, 1, 1, 1,  1, 1, 0, 0,
  // bars 9-16: four phrases transcribed from the user's a cappella (pitches kept as sung, rhythm slowed to half-time
  // so each phrase fills two bars; the last note of a phrase rings out). 1 = hold, 0 = rest.
  32,37,39,40,41,39, 1, 1, 1,40,39, 1,41, 1, 1,38,    // line 1
  34,38, 1, 1,32,34,37, 1,34,35, 1, 1, 0, 0, 0, 0,    // line 2
  40,37,38, 1, 1, 1,36, 1, 1, 1, 1,35,37,35, 1, 0,    // line 3
  33,37, 1,40, 1, 1,37,40, 1, 1,41,39,41, 1, 0, 0};   // line 4
static const uint8_t TROOT[8] = {16, 16, 17, 16, 21, 17, 23, 16};         // bass root per bar: E E F E A F B E
static const uint8_t TBASS[8] = {0, 255, 255, 0, 255, 255, 7, 255};       // per eighth: root, root, fifth (255 = none)
static const char *const TSTEP[2] = {"X.x.x.xxX.x.x.x.", "X.x.xx.xX.x.xxx."};   // footsteps per 16th, alternating bars
static const int8_t TVIB[8] = {0, 1, 2, 1, 0, -1, -2, -1};
static const uint8_t TWAVE[16] = {0x8C,0xFF,0xED,0xCD,0xDD,0xCD,0xEF,0xFC,0x83,0x00,0x12,0x32,0x22,0x32,0x10,0x03};  // hollow, reedy
static uint8_t tmu, tmf, tme, tvt, tvp, tpan;      // on, frame in eighth, eighth 0-127, lead age, vibrato phase, noise side
static uint16_t tlf;                               // lead base frequency (vibrato wobbles around it)

static void tm_start(void) {
  uint8_t i;
  disable_interrupts();
  NR30_REG = 0;
  for (i = 0; i < 16; i++) WAVERAM[i] = TWAVE[i];
  NR30_REG = 0x80;
  NR51_REG = 0xD6;                                 // ch1 left, ch2 right, ch3 both, ch4 left (moves per step)
  tmf = 21; tme = 127; tvt = 255; tvp = 0; tpan = 0; tmu = 1;      // the first update plays step 0
  enable_interrupts();
}
static void tm_stop(void) {
  disable_interrupts();
  tmu = 0;
  NR12_REG = 0; NR22_REG = 0; NR42_REG = 0; NR30_REG = 0;
  NR51_REG = 0xFF;                                 // back to centred sound for the game
  enable_interrupts();
}
static void tm_update(void) {                      // runs from the VBlank interrupt (22 frames per eighth note)
  uint8_t b, e, n, s; uint16_t f; int16_t a;
  if (!tmu) return;
  if (++tmf >= 22) { tmf = 0; tme = (tme + 1) & 127; }
  b = tme >> 3; e = tme & 7;
  if (tmf == 0) {
    if (TBASS[e] != 255) {                         // bass: short plucks on the wave channel
      f = NOTE[TROOT[b & 7] + TBASS[e]];
      NR30_REG = 0x80; NR31_REG = 0x60; NR32_REG = 0x40; NR33_REG = (uint8_t)f; NR34_REG = 0xC0 | (uint8_t)(f >> 8);
    }
    n = TLEAD[tme];
    if (n > 1) {                                   // lead: 25% pulse, slow decay
      tlf = NOTE[n]; tvt = 0; tvp = 0;
      NR21_REG = 0x40; NR22_REG = 0xA5; NR23_REG = (uint8_t)tlf; NR24_REG = 0x80 | (uint8_t)(tlf >> 8);
    }
    n = TLEAD[(tme - 1) & 127];
    if (n > 1) {                                   // echo: last eighth's note again, thin and quiet, on the other side
      f = NOTE[n];
      NR10_REG = 0; NR11_REG = 0x00; NR12_REG = 0x55; NR13_REG = (uint8_t)f; NR14_REG = 0x80 | (uint8_t)(f >> 8);
    }
  }
  if (tmf == 0 || tmf == 11) {                     // footsteps on the 16th grid
    s = (e << 1) | (tmf ? 1 : 0);
    n = TSTEP[b & 1][s];
    if (n != '.') {
      tpan ^= 1;
      NR51_REG = (uint8_t)(0x56 | (tpan ? 0x80 : 0x08));
      NR41_REG = 0; NR42_REG = (n == 'X') ? 0x51 : 0x31; NR43_REG = tpan ? 0x29 : 0x39; NR44_REG = 0x80;
    }
  }
  if (tvt != 255) {                                // vibrato on the lead once the note has settled
    if (tvt < 100) tvt++;
    tvp++;
    if (tvt >= 8) {
      a = (int16_t)((2048 - tlf) >> 6); if (a < 1) a = 1;
      s = (uint8_t)TVIB[(tvp >> 1) & 7];                         // -2..2 (a * v / 2 without mul/div)
      n = (s == 2 || s == 254) ? (uint8_t)a : (s == 1 || s == 255) ? (uint8_t)(a >> 1) : 0;
      f = (s >= 128) ? tlf - n : tlf + n;
      NR23_REG = (uint8_t)f; NR24_REG = (uint8_t)(f >> 8);          // no trigger bit: pitch only
    }
  }
}

static void snd_isr(void) { music_update(); tm_update(); jingle_update(); }

// ---------- fades: scale every palette entry towards black; the master volume follows ----------
static palette_color_t fb[32], fs[12];
static uint8_t fpn;                                  // number of BG palettes waiting in fb[] (0 = nothing pending)
static uint16_t dim(uint16_t c, uint8_t l) {
  uint8_t r = (uint8_t)(((c & 31) * l) >> 3), g = (uint8_t)((((c >> 5) & 31) * l) >> 3), b = (uint8_t)((((c >> 10) & 31) * l) >> 3);
  return (uint16_t)(r | ((uint16_t)g << 5) | ((uint16_t)b << 10));
}
static void fade_calc(uint8_t lvl, uint8_t tit) {    // lvl 0 = black .. 8 = full colour; tit = title palettes
  uint8_t i, n = tit ? 32 : 24, v = lvl > 7 ? 7 : lvl;
  const palette_color_t *p = tit ? tpal : bpal;
  for (i = 0; i < n; i++) fb[i] = dim(p[i], lvl);    // the maths is slow: do it first, write right after vsync (fade_apply)
  for (i = 0; i < 12; i++) fs[i] = dim(spal[i], lvl);
  fpn = tit ? 8 : 6;
  NR50_REG = (uint8_t)((v << 4) | v);                // master volume follows the fade
}
static void fade_apply(void) {
  if (!fpn) return;
  set_bkg_palette(0, fpn, fb);
  set_sprite_palette(0, 3, fs);
  fpn = 0;
}
static void fade_level(uint8_t lvl, uint8_t tit) { fade_calc(lvl, tit); fade_apply(); }   // immediate (LCD off)

// ---------- world ----------
static void draw_sprites(void);
static uint8_t is_nest(uint8_t x, uint8_t y) {
  return (x == nestx[0] && y == nesty[0]) || (x == nestx[1] && y == nesty[1]);
}

static void draw_cell(uint8_t x, uint8_t y) {
  uint8_t t = hgt[y][x];
  if (is_nest(x, y)) t = 4; else if (food[y][x] && t) t = 5;
  set_bkg_tile_xy(x, y, BT + t);
}

static uint8_t can_go(uint8_t x, uint8_t y, int8_t dx, int8_t dy) {
  int8_t a = (int8_t)x + dx, b = (int8_t)y + dy, d;
  if (a < 0 || b < 0 || a >= W || b >= H) return 0;
  if (hgt[b][a] == 0) return 0;
  d = (int8_t)hgt[b][a] - (int8_t)hgt[y][x];
  return d >= -1 && d <= 1;           // ants can't climb cliffs: terraform paths!
}

static uint8_t spawn(uint8_t team) {
  uint8_t i, n = 0;
  for (i = 0; i < MAXA; i++) if (ant[i].alive && ant[i].team == team) n++;
  if (n >= MAXA / 2) return 0;                    // each colony gets half the ant slots: fair fight
  for (i = 0; i < MAXA; i++) if (!ant[i].alive) {
    ant[i].x = nestx[team]; ant[i].y = nesty[team];
    ant[i].team = team; ant[i].alive = 1; ant[i].carry = 0;
    ant[i].sol = ((hatched[team]++ & 3) == 0);   // every 4th ant a colony hatches is a soldier
    return 1;
  }
  return 0;
}

static uint8_t dist(uint8_t a, uint8_t b) { return a > b ? a - b : b - a; }

static void count(uint8_t *c) {
  uint8_t i; c[0] = c[1] = 0;
  for (i = 0; i < MAXA; i++) if (ant[i].alive) c[ant[i].team]++;
}

// ---------- cartridge RAM: remembered level, records, one saved game ----------
// The ROM header says MBC5 + battery RAM (see the Makefile). Layout at 0xA000: [0] settings + records, [64] the saved game. Each block
// starts with a magic byte and ends with a rotate-xor checksum, so empty or corrupt RAM (or an emulator with no .sav) just reads as "nothing".
// Not saved: pheromone trails (they regrow) and the fast-forward / pause state.
#define SRAM ((volatile uint8_t *)0xA000)
#define CFG_AT 0
#define SAV_AT 64
#define CFG_MAGIC 0xC5
#define SAVE_MAGIC 0xA6   // bumped: the ant list grew, old saves are ignored
typedef struct { uint8_t w[3], l[3]; uint16_t t[3], s[3]; } Rec;     // per level: wins, losses, fastest win (seconds), best score
static Rec rec;
static volatile uint8_t *sp; static uint8_t ssum;
static void sram_open(uint16_t at) {
  *(volatile uint8_t *)0x0000 = 0x0A;          // enable cartridge RAM
  *(volatile uint8_t *)0x4000 = 0;             // RAM bank 0
  sp = SRAM + at; ssum = 0x5A;
}
static void sram_close(void) { *(volatile uint8_t *)0x0000 = 0x00; }
static void sw(uint8_t v) { *sp++ = v; ssum = (uint8_t)(((ssum << 1) | (ssum >> 7)) ^ v); }
static uint8_t sr(void) { uint8_t v = *sp++; ssum = (uint8_t)(((ssum << 1) | (ssum >> 7)) ^ v); return v; }

static void cfg_save(void) {
  uint8_t i; const uint8_t *r = (const uint8_t *)&rec;
  sram_open(CFG_AT);
  sw(CFG_MAGIC); sw(diff);
  for (i = 0; i < sizeof(Rec); i++) sw(r[i]);
  *sp = ssum;
  sram_close();
}
static void cfg_load(void) {
  uint8_t i, ok, *r = (uint8_t *)&rec;
  sram_open(CFG_AT);
  ok = (sr() == CFG_MAGIC);
  diff = sr();
  for (i = 0; i < sizeof(Rec); i++) r[i] = sr();
  ok = ok && (*sp == ssum) && diff < 3;
  sram_close();
  if (!ok) { for (i = 0; i < sizeof(Rec); i++) r[i] = 0; diff = 1; cfg_save(); }
}

static void save_game(void) {
  uint8_t i, x, y, b, k;
  sram_open(SAV_AT);
  sw(SAVE_MAGIC); sw(gdiff); sw(norec | (sandbox << 1));
  sw(stock[0]); sw(stock[1]); sw(qhp[0]); sw(qhp[1]); sw(hatched[0]); sw(hatched[1]);
  sw(cx); sw(cy); sw(mana); sw(appr); sw(tk);
  sw((uint8_t)etk); sw((uint8_t)(etk >> 8)); sw((uint8_t)gt); sw((uint8_t)(gt >> 8));
  for (y = 0; y < H; y++) for (x = 0; x < W; x += 4)                       // heights: 2 bits per tile
    sw(hgt[y][x] | (hgt[y][x + 1] << 2) | (hgt[y][x + 2] << 4) | (hgt[y][x + 3] << 6));
  for (y = 0; y < H; y++) for (x = 0; x < W; x += 8) {                     // food: 1 bit per tile
    b = 0; for (k = 0; k < 8; k++) if (food[y][x + k]) b |= (uint8_t)(1 << k);
    sw(b);
  }
  for (i = 0; i < MAXA; i++) { sw(ant[i].x); sw(ant[i].y); sw(ant[i].alive | (ant[i].team << 1) | (ant[i].carry << 2) | (ant[i].sol << 3)); }
  *sp = ssum;
  sram_close();
}
#define RD(v) do { uint8_t _t = sr(); if (apply) (v) = _t; } while (0)
// Reads the saved game. apply = 0 only checks it (returns 1 if intact); apply = 1 loads it into the game (check first!).
static uint8_t save_scan(uint8_t apply) {
  uint8_t i, x, y, b, k, ok;
  sram_open(SAV_AT);
  ok = (sr() == SAVE_MAGIC);
  RD(gdiff);
  b = sr(); if (apply) { norec = b & 1; sandbox = (b >> 1) & 1; }
  RD(stock[0]); RD(stock[1]); RD(qhp[0]); RD(qhp[1]); RD(hatched[0]); RD(hatched[1]);
  RD(cx); RD(cy); RD(mana); RD(appr); RD(tk);
  b = sr(); k = sr(); if (apply) etk = b | ((uint16_t)k << 8);
  b = sr(); k = sr(); if (apply) gt = b | ((uint16_t)k << 8);
  for (y = 0; y < H; y++) for (x = 0; x < W; x += 4) {
    b = sr();
    if (apply) { hgt[y][x] = b & 3; hgt[y][x + 1] = (b >> 2) & 3; hgt[y][x + 2] = (b >> 4) & 3; hgt[y][x + 3] = b >> 6; }
  }
  for (y = 0; y < H; y++) for (x = 0; x < W; x += 8) {
    b = sr();
    if (apply) for (k = 0; k < 8; k++) food[y][x + k] = (b >> k) & 1;
  }
  for (i = 0; i < MAXA; i++) {
    RD(ant[i].x); RD(ant[i].y);
    b = sr();
    if (apply) { ant[i].alive = b & 1; ant[i].team = (b >> 1) & 1; ant[i].carry = (b >> 2) & 1; ant[i].sol = (b >> 3) & 1; }
  }
  ok = ok && (*sp == ssum);
  sram_close();
  return ok;
}
static void save_erase(void) { sram_open(SAV_AT); *sp = 0; sram_close(); }

// ---------- scoring + records ----------
static uint16_t secs_played(void) {
  uint16_t s = (uint16_t)(((uint32_t)gt * 2) / 15);     // 7.5 ticks per second
  return s > 5999 ? 5999 : s ? s : 1;
}
// score for a win: 300 / 600 / 900 for the level + up to 600 for speed (one point per second under 10 minutes)
// + 5 per ant + popularity + 10 per queen HP left
static uint16_t calc_score(uint16_t secs) {
  uint16_t sc = 300 * (gdiff + 1);
  if (secs < 600) sc += 600 - secs;
  return sc + ncnt[0] * 5 + appr + qhp[0] * 10;
}
static uint8_t rec_game(uint16_t secs, uint16_t score) {   // returns bit 0 = new fastest win, bit 1 = new high score
  uint8_t d = gdiff, fl = 0;
  if (over == 1) {
    if (rec.w[d] < 99) rec.w[d]++;
    if (!rec.t[d] || secs < rec.t[d]) { rec.t[d] = secs; fl |= 1; }
    if (score > rec.s[d]) { rec.s[d] = score; fl |= 2; }
  } else if (rec.l[d] < 99) rec.l[d]++;
  cfg_save();
  return fl;
}

// ---------- popularity + elections ----------
static void apr(int8_t d) { int16_t v = (int16_t)appr + d; appr = v < 0 ? 0 : v > 99 ? 99 : (uint8_t)v; }
static void die(Ant *a) { a->alive = 0; if (a->team == 0) apr(-2); }     // every dead black ant costs you votes
static void election(void) {
  if (appr >= 50) {                                 // re-elected: foreign aid
    mana = (mana + 8 > MANA_MAX) ? MANA_MAX : mana + 8;
    sfx_mana(); say("ELECTION WON! AID");
  } else if (appr >= 25) {
    sfx_deny(); say("ELECTION: NO BONUS");
  } else {                                          // coup: the rebels loot the treasury
    stock[0] >>= 1; mana = 0; appr = 40;
    sfx_qdead(); say("COUP! COFFERS LOOTED");
  }
}

static void step_ant(Ant *a) {
  uint8_t d, t = a->team, e = t ^ 1, found = 0, bd = 0, tx, ty, de;
  int16_t sc, best = -32000;
  uint8_t soldier = !a->carry && qhp[e] && ncnt[t] >= thr[t] && a->sol;  // soldiers only march once the colony is big enough
  if (!a->carry && food[a->y][a->x]) { food[a->y][a->x] = 0; a->carry = 1; draw_cell(a->x, a->y); }
  if (a->carry) { uint8_t p = ph[a->y][a->x]; ph[a->y][a->x] = p > 215 ? 255 : p + 40; }
  for (d = 0; d < 4; d++) {
    if (!can_go(a->x, a->y, DX[d], DY[d])) continue;
    tx = a->x + DX[d]; ty = a->y + DY[d];
    if (a->carry) sc = -10 * (int16_t)(dist(tx, nestx[t]) + dist(ty, nesty[t])) + (rand() & 15);
    else if (soldier) {                                 // soldiers march straight for the enemy nest
      de = dist(tx, nestx[e]) + dist(ty, nesty[e]);
      sc = -14 * (int16_t)de + (rand() & 31);
    } else {
      sc = ph[ty][tx] + (food[ty][tx] ? 120 : 0) + (rand() & 31);   // pheromone trails
    }
    if (sc > best) { best = sc; bd = d; found = 1; }
  }
  if (found) { a->x += DX[bd]; a->y += DY[bd]; }
  if (a->carry && a->x == nestx[t] && a->y == nesty[t]) {
    a->carry = 0; if (stock[t] < 99) stock[t]++;
    if (t == 0) {
      // mana workflow, step 2: food delivered home is also tribute to the ruler
      mana = (mana + MANA_PER_FOOD > MANA_MAX) ? MANA_MAX : mana + MANA_PER_FOOD;
      apr(1);                                    // fed ants are happy ants
      sfx_food();
    }
  }
  // at the enemy nest: soldiers bite the queen, other ants steal food and run home
  if (!a->carry && qhp[e] && a->x == nestx[e] && a->y == nesty[e]) {
    if (a->sol) { if (rand() & 1) { qhp[e]--; if (e == 0) apr(-3); if (qhp[e]) sfx_hit(); else sfx_qdead(); } }
    else if (stock[e]) { stock[e]--; a->carry = 1; sfx_fight(); }
  }
}

// Game logic is sliced: each call (one per frame) moves 1/8 of the ants and decays 4 map rows of pheromone;
// every 8th call also resolves fights and runs the colony-level work. Each ant still steps once per 8 frames,
// but the work is spread evenly instead of landing as one big hitch every 8th frame.
static uint8_t slice;
static void tick_slice(void) {
  uint8_t i, j, x, y;
  for (i = slice; i < MAXA; i += 8) {
    if (!ant[i].alive) continue;
    if (hgt[ant[i].y][ant[i].x] == 0) { die(&ant[i]); continue; }            // drowned
    step_ant(&ant[i]);
  }
  for (i = slice; i < MAXA; i += 8)                                        // fights: every pair is still checked once per cycle,
    if (ant[i].alive) for (j = i + 1; j < MAXA; j++)                       // but spread over the 8 slices (no hitch every 8th frame)
      if (ant[j].alive && ant[i].team != ant[j].team && ant[i].x == ant[j].x && ant[i].y == ant[j].y)
        { if (rand() & 1) die(&ant[i]); else die(&ant[j]); sfx_fight(); if (!ant[i].alive) break; }
  if ((tk & 3) == 0) for (y = slice << 2; y < (uint8_t)((slice << 2) + 4); y++) for (x = 0; x < W; x++) if (ph[y][x]) ph[y][x]--;
  if (++slice < 8) return;
  slice = 0;
  tk++; if (gt < 65535) gt++;
  count(ncnt);
  for (i = 0; i < 2; i++) {
    if (!qhp[i]) continue;                         // no queen, no eggs
    if (stock[i] >= hcost[i] && spawn(i)) { stock[i] -= hcost[i]; if (i == 0) { sfx_spawn(); apr(1); } }
    else if (ncnt[i] == 0 && (tk & 31) == 0) spawn(i);   // emergency egg: never a dead stalemate
    if ((tk & 127) == 0 && qhp[i] < qmax[i]) qhp[i]++; // queens slowly heal
  }
  if ((tk & drn) == 0) apr(!stock[0] && ncnt[0] ? -2 : -1);   // the people are never satisfied; a hungry colony grumbles double
  if (++etk >= 450) { etk = 0; election(); }              // an election roughly every minute
  if ((tk & 7) == 0) for (i = 0; i < 2; i++) {
    x = rand() & (W - 1); y = rand() & (H - 1);
    if (hgt[y][x] && !food[y][x] && !is_nest(x, y)) { food[y][x] = 1; draw_cell(x, y); }
  }
  if ((tk & trk) == 0 && mana < MANA_MAX) mana++;   // mana workflow, step 1: slow passive trickle
}

static void bump(uint8_t cx0, uint8_t cy0, uint8_t v, uint8_t r) {
  int8_t x, y;
  for (y = (int8_t)cy0 - r; y <= (int8_t)cy0 + r; y++) for (x = (int8_t)cx0 - r; x <= (int8_t)cx0 + r; x++)
    if (x >= 0 && y >= 0 && x < W && y < H) hgt[y][x] = v;
}

// remove accidental cliffs in the generated map (the player makes the real ones)
static void smooth(void) {
  uint8_t pass, x, y, a, b;
  for (pass = 0; pass < 3; pass++) for (y = 0; y < H; y++) for (x = 0; x < W; x++) {
    a = hgt[y][x]; if (!a) continue;
    if (x + 1 < W) { b = hgt[y][x + 1]; if (b) { if (a > b + 1) hgt[y][x] = b + 1; else if (b > a + 1) hgt[y][x + 1] = a + 1; } }
    a = hgt[y][x];
    if (y + 1 < H) { b = hgt[y + 1][x]; if (b) { if (a > b + 1) hgt[y][x] = b + 1; else if (b > a + 1) hgt[y + 1][x] = a + 1; } }
  }
}

static void follow(void);
static void newgame(uint8_t load) {
  uint8_t i, k, x, y, ok = 0;
  DISPLAY_OFF;
  VBK_REG = VBK_ATTRIBUTES;                                     // world = palette 0 on every cell (nothing may leave HUD grey behind)
  for (y = 0; y < 32; y++) for (x = 0; x < 32; x++) set_bkg_tile_xy(x, y, 0);
  VBK_REG = VBK_TILES;
  if (load && save_scan(0)) { save_scan(1); ok = 1; }          // continue the saved game (checked first, so it never half-loads)
  if (ok) slotgame = 1; else { gdiff = diff; norec = (sandbox || tutor) ? 1 : 0; slotgame = 0; }
  if (gdiff > 2) gdiff = 1;
  set_rules(gdiff);
  nestx[0] = 4;  nesty[0] = 26; nestx[1] = 27; nesty[1] = 5;
  for (y = 0; y < H; y++) for (x = 0; x < W; x++) ph[y][x] = 0;
  if (!ok) {
    for (y = 0; y < H; y++) for (x = 0; x < W; x++) { hgt[y][x] = 1; food[y][x] = 0; }
    for (k = 0; k < 28; k++) { x = rand() & (W - 1); y = rand() & (H - 1); bump(x, y, 2, 1); hgt[y][x] = 3; }
    for (k = 0; k < 9; k++) {
      x = rand() & (W - 1); y = rand() & (H - 1);
      hgt[y][x] = 0;
      if (x + 1 < W) hgt[y][x + 1] = 0;
      if (y + 1 < H) hgt[y + 1][x] = 0;
      if (x + 1 < W && y + 1 < H) hgt[y + 1][x + 1] = 0;
    }
    bump(nestx[0], nesty[0], 1, 1); bump(nestx[1], nesty[1], 1, 1);
    smooth();
    for (k = 0; k < 36; k++) { x = rand() & (W - 1); y = rand() & (H - 1); if (hgt[y][x] && !is_nest(x, y)) food[y][x] = 1; }
    for (i = 0; i < MAXA; i++) ant[i].alive = 0;
    stock[0] = stock[1] = 0; qhp[0] = qmax[0]; qhp[1] = qmax[1]; hatched[0] = hatched[1] = 0;
    for (k = 0; k < 3; k++) { spawn(0); spawn(1); }
    appr = 50; etk = 0; cx = nestx[0]; cy = nesty[0] - 2; mana = DIF[gdiff].mana0; tk = 0; gt = 0;
  }
  count(ncnt);
  ff = 0; slice = 0; hdirty = 1; cheat = 0; over = 0;
  camx = 0; camy = H - VH; follow(); scx = (int16_t)camx * 8; scy = (int16_t)camy * 8;
  for (y = 0; y < H; y++) for (x = 0; x < W; x++) draw_cell(x, y);
  win_clear(); hud();
  say(ok ? "GAME LOADED" : sandbox ? "SANDBOX: NO LIMITS" : "A/B LAND START HELP");
  move_win(7, 128);                    // window = 2-row HUD at the bottom
  SCX_REG = (uint8_t)scx; SCY_REG = (uint8_t)scy;
  SHOW_WIN; SHOW_SPRITES;
  fade_level(0, 0);
  draw_sprites();
  DISPLAY_ON;
  music_start();                       // the game loop starts as the picture fades in
  for (k = 1; k <= 8; k++) { fade_calc(k, 0); for (x = 0; x < 3; x++) { vsync(); fade_apply(); } }
}

static void raise_land(void) {
  if (mana && hgt[cy][cx] < 3 && !is_nest(cx, cy)) { hgt[cy][cx]++; mana--; draw_cell(cx, cy); sfx_raise(); tev |= 2; return; }
  sfx_deny();
  say(is_nest(cx, cy) ? "NEST CANT BE EDITED" : hgt[cy][cx] >= 3 ? "ALREADY HIGHEST" : "NEED MANA");
}
static void lower_land(void) {
  if (mana && hgt[cy][cx] > 0 && !is_nest(cx, cy)) { hgt[cy][cx]--; mana--; draw_cell(cx, cy); sfx_lower(); tev |= 4; return; }
  sfx_deny();
  say(is_nest(cx, cy) ? "NEST CANT BE EDITED" : hgt[cy][cx] == 0 ? "ALREADY WATER" : "NEED MANA");
}
// mana workflow, step 3: embezzle. Skim colony food (that would hatch ants) into mana, at a cost in popularity.
static void offering(void) {
  if (stock[0] < OFFER_FOOD) { sfx_deny(); say("NEED 2 FOOD"); return; }
  if (mana >= MANA_MAX) { sfx_deny(); say("MANA IS FULL"); return; }
  stock[0] -= OFFER_FOOD;
  mana = (mana + OFFER_MANA > MANA_MAX) ? MANA_MAX : mana + OFFER_MANA;
  apr(-5); sfx_mana(); say("EMBEZZLED! P DOWN");
}
static void flood(void) {
  int8_t x, y;
  if (mana < 8) { sfx_deny(); say("FLOOD NEEDS 8 MANA"); return; }
  mana -= 8; sfx_flood(); tev |= 8;
  for (y = (int8_t)cy - 1; y <= (int8_t)cy + 1; y++) for (x = (int8_t)cx - 1; x <= (int8_t)cx + 1; x++)
    if (x >= 0 && y >= 0 && x < W && y < H && hgt[y][x] && !is_nest(x, y)) { hgt[y][x]--; draw_cell(x, y); }
}

// ---------- camera ----------
static void follow(void) {            // dead-zone camera: scrolls when the cursor nears an edge
  uint8_t t;
  if (cx < camx + 3) camx = cx > 3 ? cx - 3 : 0;
  else if (cx + 3 >= camx + VW) { t = cx + 4 - VW; camx = t > W - VW ? W - VW : t; }
  if (cy < camy + 3) camy = cy > 3 ? cy - 3 : 0;
  else if (cy + 3 >= camy + VH) { t = cy + 4 - VH; camy = t > H - VH ? H - VH : t; }
}
static void scroll_step(void) {       // glide to the target 4px per frame
  int16_t tx = (int16_t)camx * 8, ty = (int16_t)camy * 8;
  if (scx < tx) { scx += 4; if (scx > tx) scx = tx; } else if (scx > tx) { scx -= 4; if (scx < tx) scx = tx; }
  if (scy < ty) { scy += 4; if (scy > ty) scy = ty; } else if (scy > ty) { scy -= 4; if (scy < ty) scy = ty; }
}
static void place(uint8_t s, uint8_t x, uint8_t y) {
  int16_t sx = (int16_t)x * 8 - scx, sy = (int16_t)y * 8 - scy;
  if (sx > -8 && sx < 160 && sy > -8 && sy < 128) move_sprite(s, (uint8_t)(sx + 8), (uint8_t)(sy + 16));
  else move_sprite(s, 0, 0);
}
static void draw_sprites(void) {
  uint8_t i, s = 0;
  int16_t sx, sy;
  for (i = 0; i < MAXA && s < NSPR; i++) {            // only ants inside the view get one of the NSPR sprites
    if (!ant[i].alive) continue;
    sx = (int16_t)ant[i].x * 8 - scx; sy = (int16_t)ant[i].y * 8 - scy;
    if (sx > -8 && sx < 160 && sy > -8 && sy < 128) {
      move_sprite(s, (uint8_t)(sx + 8), (uint8_t)(sy + 16)); set_sprite_prop(s, ant[i].team); s++;
    }
  }
  while (s < NSPR) move_sprite(s++, 0, 0);
  for (i = 0; i < 2; i++) {
    if (qhp[i]) place(QSPR + i, nestx[i], nesty[i]); else move_sprite(QSPR + i, 0, 0);
  }
  place(QSPR + 2, cx, cy);
}

// ---------- screens ----------
// Title: night sky with twinkling stars and a moon, the gold logo with a shine that sweeps across it, rolling hills
// with ants marching along the grass, the stereo title theme, and a fade in / fade out.
static uint8_t band(uint8_t y) { return y < 6 ? 0 : y < 10 ? 1 : 2; }      // sky palette per window row
static void title_scene(void) {
  uint8_t x, y, i, t, p;
  char c;
  for (y = 0; y < 18; y++) for (x = 0; x < 20; x++) {
    c = SCN[y][x]; t = FT;
    for (i = 0; SCKEY[i]; i++) if (SCKEY[i] == c) { t = TS + i; break; }
    set_win_tile_xy(x, y, t);
  }
  VBK_REG = VBK_ATTRIBUTES;
  for (y = 0; y < 18; y++) for (x = 0; x < 20; x++) {
    c = SCN[y][x]; p = band(y);
    for (i = 0; SCKEY[i]; i++) if (SCKEY[i] == c) { if (i >= 7) p = 4; break; }   // grass, slopes, hill and soil use palette 4
    set_win_tile_xy(x, y, p);
  }
  VBK_REG = VBK_TILES;
}
static void logo_shine(int8_t col) {              // brighten the logo columns around `col` (palettes 6 and 7 vs normal 3)
  uint8_t i, d, p;
  VBK_REG = VBK_ATTRIBUTES;
  for (i = 0; i < 11; i++) {
    d = (int8_t)i > col ? (uint8_t)(i - col) : (uint8_t)(col - i);
    p = d == 0 ? 7 : d == 1 ? 6 : 3;
    set_win_tile_xy(4 + i, 3, p); set_win_tile_xy(4 + i, 4, p);
  }
  VBK_REG = VBK_TILES;
}
static void twinkle(uint8_t ph) {                 // bright stars ('*') alternate between a plus and a dot, staggered
  uint8_t x, y;
  for (y = 0; y < 11; y++) for (x = 0; x < 20; x++)
    if (SCN[y][x] == '*') set_win_tile_xy(x, y, (((x + y) & 1) ^ ph) ? TS + 1 : TS);
}
static uint8_t tfr, tf3, tsh, tblink, wx[5];
static void title_tick(void) {                    // one title frame
  uint8_t i, on;
  vsync(); fade_apply(); seed += DIV_REG + 1;      // palettes first (we are in vblank); seed from how long you wait
  tfr++;
  if (++tf3 >= 3) { tf3 = 0; if (++tsh >= 48) tsh = 0; if (tsh <= 16) logo_shine((int8_t)tsh - 2); }
  if ((tfr & 31) == 0) twinkle((tfr >> 5) & 1);
  on = (tfr & 63) < 44;
  if (on != tblink) { tblink = on; put_str(4, 9, on ? "PRESS START" : "           "); }
  for (i = 0; i < 5; i++) {                       // 3 black ants march right, 2 red ants march left
    if (!(tfr & 1)) { if (i < 3) { if (++wx[i] >= 168) wx[i] = 0; } else wx[i] = wx[i] ? wx[i] - 1 : 167; }
    set_sprite_tile(i, TW + (((tfr >> 3) + i) & 1));
    move_sprite(i, wx[i], i < 3 ? 138 : 141);
  }
}
static void title_fade(uint8_t from, uint8_t to) {     // 4 frames per brightness step, scenery and music keep running
  uint8_t l = from, k;
  for (;;) {
    fade_calc(l, 1);                               // written by the first title_tick, right after its vsync
    for (k = 0; k < 4; k++) title_tick();
    if (l == to) break;
    if (l < to) l++; else l--;
  }
}
static void diff_draw(void) { put_str(7, 7, DNAME[diff]); }
static void title_paint(void) {
  win_clear();
  title_scene();
  title_logo(4, 3);
  put_str(2, 6, "THE RULER OF YOU");
  put_char(5, 7, '<'); put_char(14, 7, '>'); attr(5, 7, 10, 3);          // gold level picker (LEFT / RIGHT)
  diff_draw();
  if (hassave) put_str(1, 10, "UP:LOAD  B:RECORDS"); else put_str(5, 10, "B: RECORDS");
  put_str(2, 11, "A: LEARN TO PLAY");
  put_str(1, 12, "HOLD SEL: SANDBOX");
}
// Records: wins, losses, fastest win and best score for each level. Hold SELECT + B for 2 s to erase them. START / A goes back.
static void records_draw(void) {
  uint8_t d, y;
  win_clear();
  put_str(0, 0, "RECORDS"); attr(0, 0, 7, 3);
  for (d = 0; d < 3; d++) {
    y = 2 + d * 4;
    put_str(0, y, DNAME[d]); attr(0, y, 6, 3);
    put_str(7, y, "WON"); put_num(10, y, rec.w[d]); put_str(13, y, "LOST"); put_num(17, y, rec.l[d]);
    put_str(0, y + 1, "FASTEST"); put_time(8, y + 1, rec.t[d]);
    put_str(0, y + 2, "SCORE"); put_dec(8, y + 2, rec.s[d], 5);
  }
  put_str(0, 15, "HOLD SEL B: ERASE");
  put_str(0, 17, "START: BACK");
}
static void records_screen(void) {
  uint8_t k, d, hold = 0;
  DISPLAY_OFF; HIDE_SPRITES;
  records_draw();
  DISPLAY_ON;
  waitpadup();
  while (1) {
    vsync(); k = joypad();
    if (k & (J_START | J_A)) break;
    if ((k & (J_SELECT | J_B)) == (J_SELECT | J_B)) {
      if (hold < 255) hold++;
      if (hold == 120) {
        for (d = 0; d < 3; d++) rec.w[d] = rec.l[d] = rec.t[d] = rec.s[d] = 0;
        cfg_save(); records_draw(); put_str(0, 15, "RECORDS ERASED     ");
      }
    } else hold = 0;
  }
  DISPLAY_OFF;
  waitpadup();
}
static void title(void) {
  uint8_t k, i, x, y, p, prev;
  waitpadup();                         // e.g. START that skipped the boot logo is still held
  DISPLAY_OFF;
  HIDE_SPRITES;
  hassave = save_scan(0); loadreq = 0;
  title_paint();
  wx[0] = 14; wx[1] = 62; wx[2] = 112; wx[3] = 150; wx[4] = 44;
  for (i = 0; i < 5; i++) set_sprite_prop(i, i < 3 ? 0 : (1 | 0x20));   // red ants: palette 1, flipped to face left
  tfr = 0; tf3 = 0; tsh = 40; tblink = 255;
  SCX_REG = 0; SCY_REG = 0;
  move_win(7, 0); SHOW_WIN; SHOW_SPRITES;
  fade_level(0, 1);                    // black before the LCD comes on
  DISPLAY_ON;
  tm_start();
  title_fade(0, 8);
  prev = joypad();
  for (;;) {
    k = joypad(); p = k & ~prev; prev = k;
    if (k & (J_START | J_A)) break;
    if ((p & J_UP) && hassave) { loadreq = 1; k = J_START; break; }       // UP: continue the saved game
    if (p & (J_LEFT | J_RIGHT)) { diff = (p & J_RIGHT) ? (diff == 2 ? 0 : diff + 1) : (diff ? diff - 1 : 2); diff_draw(); }
    if (p & J_B) { records_screen(); title_paint(); SHOW_SPRITES; DISPLAY_ON; tblink = 255; prev = joypad(); }
    title_tick();
  }
  tutor = (k & J_START) ? 0 : 1;       // A alone = guided tutorial
  sandbox = ((k & J_START) && (k & J_SELECT)) ? 1 : 0;   // hold SELECT when pressing START: sandbox (infinite mana, queens can't die)
  cfg_save();                          // remember the chosen level
  title_fade(8, 0);
  tm_stop();
  DISPLAY_OFF;
  for (i = 0; i < 5; i++) { set_sprite_tile(i, 0); set_sprite_prop(i, 0); move_sprite(i, 0, 0); }
  VBK_REG = VBK_ATTRIBUTES;            // give every window cell back to the HUD palette
  for (y = 0; y < 18; y++) for (x = 0; x < 20; x++) set_win_tile_xy(x, y, 1);
  VBK_REG = VBK_TILES;
  fade_level(8, 0);                    // game palettes at full colour, volume back to max
  waitpadup();
  initrand(seed);
}

// ---------- ANT EYE: first-person 3D view from a black ant ----------
// SELECT+START. 20 columns x 12 window tile rows live in VRAM bank 1 and are redrawn from a ray march over the
// heightmap: checkerboard land, blue water, brown hills, red/black ant posts and tall queen towers.
#define VX 20
#define VR 12
#define VY0 2           // window row of the first view row (HUD above, help text below)
#define VN 24           // ray steps, half a cell each
static const int8_t SIN16[16] = {0, 24, 45, 59, 64, 59, 45, 24, 0, -24, -45, -59, -64, -59, -45, -24};
static const uint8_t BBH[VN + 1] = {0, 40, 32, 21, 16, 12, 10, 9, 8, 7, 6, 5, 5, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2};
// pixel class (0 sky, 1/2 checker land, 3 hill, 4 water, 5 red, 6 black) -> colour of palette 3 / 4 / 5
static const uint8_t PMAP[3][7] = {{0, 1, 2, 3, 0, 0, 0}, {0, 2, 3, 3, 1, 0, 0}, {0, 3, 3, 3, 0, 1, 2}};
static int8_t OFF[7][VN + 1];                     // screen offset of terrain: [height - eye level + 3][depth]
static uint8_t occ[H][W], cls[VR * 8], vang;      // occ: 1 black ant, 2 red ant, 3/4 black/red queen tower

static void view_init(void) {
  uint8_t d, n; int16_t v;
  for (d = 0; d < 7; d++) for (n = 1; n <= VN; n++) {
    v = ((int16_t)(((int8_t)d - 3) * 4 - 3) * 16) / n;
    OFF[d][n] = v > 64 ? 64 : v < -64 ? -64 : (int8_t)v;
  }
}

static void view_col(uint8_t c, uint8_t vx, uint8_t vy, uint8_t eh) {
  int16_t t = (int16_t)c * 2 - 19, px = (int16_t)vx * 256 + 128, py = (int16_t)vy * 256 + 128, yt, a, e, r, rx, ry;
  uint8_t n, x, y, h, o, col, lim = VR * 8, lb;
  rx = (int16_t)SIN16[(vang + 4) & 15] * 32 - (int16_t)SIN16[vang] * t;
  ry = (int16_t)SIN16[vang] * 32 + (int16_t)SIN16[(vang + 4) & 15] * t;
  rx >>= 4; ry >>= 4;                                // one step = half a cell forward
  for (n = 0; n < VR * 8; n++) cls[n] = 0;
  for (n = 1; n <= VN && lim; n++) {
    px += rx; py += ry;
    if (px < 0 || py < 0 || px >= W * 256 || py >= H * 256) break;
    x = (uint8_t)(px >> 8); y = (uint8_t)(py >> 8);
    h = hgt[y][x];
    yt = 48 - OFF[h + 3 - eh][n];
    lb = lim;
    if (yt < lb) {                                   // terrain pokes above everything nearer: paint it
      a = yt < 0 ? 0 : yt;
      col = h == 0 ? 4 : h == 3 ? 3 : ((x + y) & 1) ? 1 : 2;
      for (r = a; r < lb; r++) cls[r] = col;
      lim = (uint8_t)a;
    }
    o = occ[y][x];
    if (o && !(x == vx && y == vy) && (uint8_t)(px - 64) < 128 && (uint8_t)(py - 64) < 128) {   // centre of the cell only
      a = BBH[n]; if (o > 2) a <<= 1;
      a = yt - a;                                    // top row of the post
      e = yt < lb ? yt : lb;
      if (a < 0) a = 0;
      col = (o & 1) ? 6 : 5;
      for (r = a; r < e; r++) cls[r] = col;
      if (a < lim) lim = (uint8_t)a;
    }
  }
}

static uint8_t tcol[VR * 16];
static void occ_set(uint8_t on) {                    // mark ants / queen towers on the occupancy map (and clear it again)
  uint8_t i;
  for (i = 0; i < MAXA; i++) if (ant[i].alive) occ[ant[i].y][ant[i].x] = on ? ant[i].team + 1 : 0;
  for (i = 0; i < 2; i++) if (qhp[i]) occ[nesty[i]][nestx[i]] = on ? 3 + i : 0;
}
// Draws view columns c0..c1-1. A whole column's 12 tiles are built in RAM and sent with ONE set_bkg_data call.
static void view_cols(uint8_t vx, uint8_t vy, uint8_t c0, uint8_t c1) {
  uint8_t c, r, k, v, p, m, eh = hgt[vy][vx], *t;
  VBK_REG = VBK_ATTRIBUTES;                          // tile data + attributes both go to bank 1 here
  for (c = c0; c < c1; c++) {
    view_col(c, vx, vy, eh);
    t = tcol;
    for (r = 0; r < VR; r++) {
      m = 0;
      for (k = 0; k < 8; k++) { v = cls[r * 8 + k]; if (v == 4) m |= 1; else if (v > 4) m |= 2; }
      p = (m & 2) ? 2 : (m & 1) ? 1 : 0;             // palette: ants > water > plain land
      for (k = 0; k < 8; k++) { v = PMAP[p][cls[r * 8 + k]]; *t++ = (v & 1) ? 0xFF : 0; *t++ = (v & 2) ? 0xFF : 0; }
      set_win_tile_xy(c, VY0 + r, 8 | (3 + p));      // bit 3 = tile from VRAM bank 1
    }
    set_bkg_data(c * VR, VR, tcol);
  }
  VBK_REG = VBK_TILES;
}
static const char *const COMPASS[8] = {"E ", "SE", "S ", "SW", "W ", "NW", "N ", "NE"};   // vang 0 looks east, turning right = clockwise
static void eye_status(uint8_t vx, uint8_t vy) {
  put_str(0, 17, "X"); put_num(1, 17, vx); put_str(4, 17, "Y"); put_num(5, 17, vy);
  put_str(9, 17, "H"); put_char(10, 17, '0' + hgt[vy][vx]);
  put_str(12, 17, "FACING"); put_str(18, 17, COMPASS[vang >> 1]);
}
static void eye_step(uint8_t *vx, uint8_t *vy, int8_t dir) {   // walk one cell forward (dir 1) or back (-1), ants' rules: no cliffs, no water
  int8_t fx = SIN16[(vang + 4) & 15], fy = SIN16[vang], dx = 0, dy = 0;
  if ((fx < 0 ? -fx : fx) >= (fy < 0 ? -fy : fy)) dx = fx < 0 ? -1 : 1; else dy = fy < 0 ? -1 : 1;
  dx *= dir; dy *= dir;
  if (can_go(*vx, *vy, dx, dy)) { *vx += dx; *vy += dy; }
}

static uint8_t vok(uint8_t i) { return i < MAXA ? (ant[i].alive && ant[i].team == 0) : qhp[0] > 0; }

static void eye(void) {                              // time stands still while you look through a black ant's eyes
  uint8_t i, x, y, k, p, prev, vi = MAXA, best = 255, d, rep = 0, go = 1, vx = 0, vy = 0, vcol = VX, dirs, last = 0;
  tev |= 16;
  for (i = 0; i < MAXA; i++) if (vok(i)) { d = dist(ant[i].x, cx) + dist(ant[i].y, cy); if (d < best) { best = d; vi = i; } }
  HIDE_SPRITES;
  VBK_REG = VBK_TILES;
  for (x = 0; x < VX; x++) for (y = 0; y < VR; y++) set_win_tile_xy(x, VY0 + y, x * VR + y);
  for (y = 14; y < 18; y++) for (x = 0; x < 20; x++) set_win_tile_xy(x, y, FT);
  put_str(0, 14, "A:NEXT ANT B:GO HERE");
  put_str(0, 15, "L/R TURN  U/D WALK");
  put_str(0, 16, "START BACK TIME STOP");
  occ_set(1);                                        // ants cannot move in here: mark them once
  move_win(7, 0);
  prev = joypad();
  while (1) {
    if (go) {                                        // 1 = jump to the chosen ant, 2 = same spot (turned / walked)
      if (go == 1) { if (vi < MAXA) { vx = ant[vi].x; vy = ant[vi].y; } else { vx = nestx[0]; vy = nesty[0]; } }
      go = 0; vcol = 0; eye_status(vx, vy);
    }
    vsync();
    if (vcol < VX) { view_cols(vx, vy, vcol, vcol + 4); vcol += 4; }   // 4 columns per frame: the view sweeps in, input stays live
    k = joypad(); p = k & ~prev; prev = k;
    if (p & J_START) break;
    if (p & J_B) { cx = vx; cy = vy; break; }          // transfer: the cursor jumps to where you were looking from
    if (p & J_A) { i = 0; do { vi = (vi == MAXA) ? 0 : vi + 1; } while (!vok(vi) && ++i <= MAXA); sfx_food(); go = 1; }
    dirs = k & (J_LEFT | J_RIGHT | J_UP | J_DOWN);
    if (dirs != last) { rep = 0; last = dirs; }
    if (dirs) {
      if (rep == 0 || (rep >= 8 && !(rep & 3))) {
        if (dirs & J_RIGHT) { vang = (vang + 1) & 15; go = 2; }
        else if (dirs & J_LEFT) { vang = (vang + 15) & 15; go = 2; }
        else { x = vx; y = vy; eye_step(&vx, &vy, (dirs & J_UP) ? 1 : -1); if (vx != x || vy != y) go = 2; }
      }
      if (rep < 250) rep++;
    }
  }
  occ_set(0);
  win_clear(); hdirty = 1;
  move_win(7, 128); SHOW_SPRITES;
  waitpadup();
}

// ---------- TUTORIAL: interactive lessons (title screen: press A) ----------
// Each lesson is a full-screen card (START next, B skip), then - if it has a task - a live hint on the HUD until you do it.
#define TN 10
static const uint8_t TEV[TN] = {0, 1, 2, 4, 0, 8, 16, 0, 0, 0};     // event bit that completes each lesson (0 = read only)
static const char *const THINT[TN] = {0, "TRY: MOVE THE CURSOR", "TRY: PRESS A: RAISE", "TRY: PRESS B: LOWER", 0,
  "TAP SELECT TO FLOOD", "SEL START: ANT EYE", 0, 0, 0};
static const char *const TCARD[TN] = {
 "WELCOME RULER!\n"
  "YOU RULE THE BLACK\n"
  "ANTS OF EMPIRE ANTS\n"
  "YOU CANT GIVE THEM\n"
  "ORDERS: INSTEAD YOU\n"
  "SHAPE THE LAND AND\n"
  "THEY WALK AROUND IT\n"
  "\n"
  "GOAL: KILL THE RED\n"
  "QUEEN BEFORE THEY\n"
  "KILL YOURS\n",
 "1/8 THE CURSOR\n"
  "THE YELLOW FRAME IS\n"
  "YOUR CURSOR: LAND\n"
  "TOOLS WORK ON THE\n"
  "TILE UNDER IT\n"
  "\n"
  "D PAD MOVES IT\n"
  "HOLD TO REPEAT\n"
  "THE MAP SCROLLS NEAR\n"
  "THE EDGE\n"
  "\n"
  "NOW TRY IT!\n",
 "2/8 RAISE LAND\n"
  "LAND HAS 4 HEIGHTS:\n"
  "0 WATER   1 SAND\n"
  "2 GRASS   3 HILL\n"
  "\n"
  "A RAISES THE TILE\n"
  "UNDER THE CURSOR\n"
  "COST: 1 MANA\n"
  "ANTS CANT CLIMB MORE\n"
  "THAN 1 STEP: BUILD\n"
  "RAMPS AND STAIRS!\n"
  "NESTS CANT BE EDITED\n",
 "3/8 LOWER LAND\n"
  "B LOWERS THE TILE\n"
  "COST: 1 MANA\n"
  "\n"
  "LEVEL 0 IS WATER:\n"
  "ANTS CANT WALK ON IT\n"
  "AND DROWN IF FLOODED\n"
  "DIG MOATS TO STOP\n"
  "RED ANTS: RAISE LAND\n"
  "TO BRIDGE GAPS\n",
 "4/8 MANA\n"
  "MP IS YOUR MANA:\n"
  "EVERY EDIT COSTS MP\n"
  "\n"
  "MP COMES FROM:\n"
  " SLOW TRICKLE\n"
  " FOOD CARRIED HOME\n"
  " ELECTION AID\n"
  "\n"
  "SEL A EMBEZZLES 2\n"
  "FOOD INTO 4 MP BUT\n"
  "P DROPS BY 5\n",
 "5/8 FLOOD\n"
  "TAP SELECT ALONE:\n"
  "LOWERS A 3X3 AREA BY\n"
  "ONE LEVEL: COST 8 MP\n"
  "\n"
  "ANTS ON TILES THAT\n"
  "HIT LEVEL 0 DROWN:\n"
  "GREAT AGAINST RED\n"
  "ARMIES BUT CAREFUL\n"
  "WITH YOUR OWN!\n"
  "MP REFILLED FOR YOU\n",
 "6/8 ANT EYE\n"
  "SEE THE WORLD LIKE\n"
  "A BLACK ANT:\n"
  "HOLD SELECT AND TAP\n"
  "START\n"
  "L R  TURN\n"
  "U D  WALK\n"
  "A    NEXT ANT\n"
  "B    JUMP CURSOR TO\n"
  "     THIS SPOT\n"
  "START  BACK\n"
  "RED POSTS: ENEMIES\n"
  "TALL: QUEENS\n",
 "7/8 THE COLONY\n"
  "BLACK ANTS FIND FOOD\n"
  "AND CARRY IT HOME\n"
  "3 FOOD HATCHES A\n"
  "NEW ANT\n"
  "EVERY 4TH IS A\n"
  "SOLDIER: WITH 8 ANTS\n"
  "THEY MARCH ON THE\n"
  "RED NEST\n"
  "ANTS FOLLOW TRAILS:\n"
  "MAKE EASY PATHS!\n",
 "8/8 POPULARITY\n"
  "P IS POPULARITY\n"
  "FOOD AND NEW ANTS\n"
  "RAISE P: DEAD ANTS\n"
  "AND HUNGER CUT IT\n"
  "\n"
  "ELECTION EVERY MIN:\n"
  "P 50 UP: 8 MP AID\n"
  "P UNDER 25: COUP!\n"
  "COFFERS LOOTED\n",
 "READY TO RULE!\n"
  "KILL THE RED QUEEN\n"
  "TO WIN: LOSE YOURS\n"
  "AND ITS OVER\n"
  "\n"
  "START: PAUSE HELP\n"
  "SEL B: FAST FORWARD\n"
  "\n"
  "LONG LIVE THE QUEEN!\n"
  "GOOD LUCK!\n",
};

static void tut_card(uint8_t i) {
  uint8_t r, k, prev;
  const char *t;
  win_clear();
  t = put_line(1, TCARD[i]);                           // title row 1, body from row 3
  for (r = 3; *t && r < 15; r++) t = put_line(r, t);
  put_str(0, 16, "START: NEXT  B: SKIP");
  HIDE_SPRITES; move_win(7, 0);
  prev = joypad();
  while (1) {
    vsync();
    k = joypad();
    if ((k & ~prev) & J_START) break;
    if ((k & ~prev) & J_B) { tut = 0; break; }
    prev = k;
  }
  win_clear(); hdirty = 1;
  move_win(7, 128); SHOW_SPRITES; waitpadup();
}
static void tut_enter(void) {                          // show lessons until one needs the player to do something
  while (tut) {
    if (tut > TN) { tut = 0; say("GOOD LUCK RULER!"); sfx_mana(); break; }
    tut_card(tut - 1);
    if (!tut) { say("TUTORIAL SKIPPED"); break; }
    tev = 0; lcx = cx; lcy = cy;
    if (mana < 10) mana = 10;                          // always enough MP to practise
    if (tut == 6) mana = MANA_MAX;                     // flood costs 8
    if (TEV[tut - 1]) break;
    tut++;
  }
}

static void results_card(uint16_t secs, uint16_t score, uint8_t fl) {   // end of a counted game: this run + the level's records
  uint8_t d = gdiff;
  win_clear();
  put_str(0, 1, over == 1 ? "YOU WIN!" : "COLONY LOST!"); attr(0, 1, 12, 2);
  put_str(0, 3, "LEVEL"); put_str(8, 3, DNAME[d]);
  put_str(0, 4, "TIME"); put_time(8, 4, secs);
  if (over == 1) { put_str(0, 5, "SCORE"); put_dec(8, 5, score, 5); }
  if (fl & 1) { put_str(0, 7, "NEW FASTEST TIME!"); attr(0, 7, 17, 2); }
  if (fl & 2) { put_str(0, 8, "NEW HIGH SCORE!"); attr(0, 8, 15, 2); }
  put_str(0, 10, "RECORDS"); put_str(8, 10, DNAME[d]); attr(0, 10, 14, 2);
  put_str(0, 11, "WON"); put_num(4, 11, rec.w[d]); put_str(8, 11, "LOST"); put_num(13, 11, rec.l[d]);
  put_str(0, 12, "FASTEST"); put_time(8, 12, rec.t[d]);
  put_str(0, 13, "SCORE"); put_dec(8, 13, rec.s[d], 5);
  put_str(0, 16, "START: CONTINUE");
  HIDE_SPRITES; move_win(7, 0);
  while (1) { vsync(); if (joypad() & J_START) break; }
  waitpadup();
}

static void play(void) {
  uint8_t k, prev = 0, p, dirs, last = 0, rep = 0, fire, t = 4, ki = 0, paused = 0, selused = 0, selprev = 0, n, qask = 0, sconf = 0, fl = 0;
  uint16_t secs, score;
  if (tutor) { tut = 1; tut_enter(); }
  while (!over) {
    vsync();
    SCX_REG = (uint8_t)scx; SCY_REG = (uint8_t)scy;
    k = joypad(); p = k & ~prev; prev = k;
    if ((p & J_START) && (k & J_SELECT) && !paused) { selused = 1; eye(); continue; }   // SELECT+START: ant eye
    if (p & J_START) {                 // START: pause + help screen
      paused ^= 1;
      if (paused) { help_open(); qask = sconf = 0; move_win(7, 0); HIDE_SPRITES; } else { move_win(7, 128); SHOW_SPRITES; }
    }
    if (paused) {                      // UP/DOWN scrolls the help text (hold to repeat); A saves, B (twice) quits to the title
      if (p & J_A) {
        if (tut) put_line(16, "NO SAVE IN LESSONS");
        else if (hassave && !slotgame && !sconf) { sconf = 1; qask = 0; put_line(16, "A AGAIN: OVERWRITE"); }
        else { save_game(); hassave = save_scan(0); if (hassave) slotgame = 1; sconf = qask = 0; put_line(16, hassave ? "GAME SAVED!" : "SAVE FAILED"); }
      }
      if (p & J_B) {
        if (qask) over = 3;
        else { qask = 1; sconf = 0; put_line(16, "B AGAIN: QUIT"); }
      }
      dirs = k & (J_UP | J_DOWN);
      if (dirs != last) { rep = 0; last = dirs; }
      if (dirs) {
        if (rep == 0 || (rep >= 12 && !(rep & 3))) help_scroll((dirs & J_DOWN) ? 1 : -1);
        if (rep < 250) rep++;
      }
      continue;
    }
    dirs = k & (J_LEFT | J_RIGHT | J_UP | J_DOWN);
    if (dirs != last) { rep = 0; last = dirs; }
    if (dirs) {                        // hold to repeat after a short delay
      fire = (rep == 0) || (rep >= 10 && (rep % 3) == 1);
      if (rep < 250) rep++;
      if (fire) {
        if ((dirs & J_LEFT) && cx > 0) cx--;
        if ((dirs & J_RIGHT) && cx < W - 1) cx++;
        if ((dirs & J_UP) && cy > 0) cy--;
        if ((dirs & J_DOWN) && cy < H - 1) cy++;
      }
    }
    if (p) {                           // cheat code tracker
      if (p == CHEAT[ki]) { if (++ki == 10) { ki = 0; cheat = 1; norec = 1; sfx_mana(); say("CHEAT ON! INFINITE"); } }
      else ki = (p == CHEAT[0]) ? 1 : 0;
    }
    if (k & J_SELECT) {               // SELECT is a modifier: SEL+A embezzle, SEL+B fast forward, alone (on release) flood
      if (p & J_SELECT) selused = 0;
      if (p & J_A) { offering(); selused = 1; }
      if (p & J_B) { ff ^= 1; say(ff ? "FAST FORWARD ON" : "FAST FORWARD OFF"); selused = 1; }
    } else {
      if (selprev && !selused) flood();
      if (p & J_A) raise_land();
      if (p & J_B) lower_land();
    }
    selprev = k & J_SELECT;
    if (tut && (cx != lcx || cy != lcy)) { tev |= 1; lcx = cx; lcy = cy; }
    if (tut && (tev & TEV[tut - 1])) { sfx_mana(); tut++; tut_enter(); }     // task done: next lesson
    if (cheat) { mana = MANA_MAX; stock[0] = 99; appr = 99; }
    if (sandbox) { mana = MANA_MAX; qhp[0] = qmax[0]; qhp[1] = qmax[1]; appr = 99; }
    if (tut) { qhp[0] = qmax[0]; qhp[1] = qmax[1]; if (appr < 50) appr = 50; }          // no game over mid-lesson
    follow(); scroll_step();
    for (n = ff ? 4 : 1; n; n--) tick_slice();     // fast forward = 4 slices per frame
    if (++t >= 8) {
      t = 0; count(ncnt);
      if (tut && !msgt && THINT[tut - 1]) { msg = THINT[tut - 1]; msgt = 1; }   // keep the lesson goal on the HUD
      hud();
    }
    if (!qhp[1]) over = 1; else if (!qhp[0]) over = 2;
    draw_sprites();
  }
  music_stop();
  if (over == 3) return;               // quit from the pause menu: the title screen takes over (a save, if any, is kept)
  count(ncnt);
  secs = secs_played(); score = (over == 1) ? calc_score(secs) : 0;
  if (slotgame) { save_erase(); slotgame = 0; hassave = 0; }   // a finished game uses up its save: no reloading after a loss
  attr(0, 1, 20, 1);
  put_str(0, 1, over == 1 ? "YOU WIN! PRESS START" : "COLONY LOST! START  ");
  if (over == 1) jingle(WIN_TUNE, 6); else jingle(LOSE_TUNE, 4);
  while (1) { vsync(); if (joypad() & J_START) break; }
  waitpadup();
  if (!norec) { fl = rec_game(secs, score); results_card(secs, score, fl); }
}

void main(void) {
  uint8_t i, x, y;
  static uint8_t buf[40 * 16];                           // static: keep 640 bytes off the small stack
  dippinn_logo_play();                                   // DippInn boot logo (~8 s, START skips)
  add_VBL(snd_isr);                                      // music + jingles tick in the VBlank interrupt from here on
  NR52_REG = 0x80; NR51_REG = 0xFF; NR50_REG = 0x77;     // sound on, all channels, full volume
  DISPLAY_OFF;
  set_bkg_data(BT, 8, BGT);                              // 6 terrain tiles + 2 mana-bar tiles
  for (i = 0; i < 40; i++) mk_glyph(buf + i * 16, FONT[i]);
  set_bkg_data(FT, 40, buf);
  title_tiles(buf);
  set_bkg_data(TT, 13, buf);
  set_bkg_data(TS, 12, TAT);
  mk_glyph(buf, 012421); mk_glyph(buf + 16, 042124);     // '<' and '>' for the level picker
  set_bkg_data(AR, 2, buf);
  cfg_load();                                            // remembered level + records from cartridge RAM
  set_sprite_data(0, 5, SPT);
  set_bkg_palette(0, 6, bpal);
  view_init();
  set_sprite_palette(0, 3, spal);
  VBK_REG = VBK_ATTRIBUTES;                              // BG layer: palette 0, window: palette 1
  for (y = 0; y < 32; y++) for (x = 0; x < 32; x++) set_bkg_tile_xy(x, y, 0);
  for (y = 0; y < 18; y++) for (x = 0; x < 20; x++) set_win_tile_xy(x, y, 1);
  VBK_REG = VBK_TILES;
  LCDC_REG = (uint8_t)((LCDC_REG | LCDCF_WIN9C00) & (uint8_t)~LCDCF_BG9C00); // window map 9C00, world map 9800
  SPRITES_8x8;
  for (i = 0; i < NSPR; i++) set_sprite_tile(i, 0);
  set_sprite_tile(QSPR, 2);     set_sprite_prop(QSPR, 0);       // black queen
  set_sprite_tile(QSPR + 1, 2); set_sprite_prop(QSPR + 1, 1);   // red queen
  set_sprite_tile(QSPR + 2, 1); set_sprite_prop(QSPR + 2, 2);   // cursor
  SHOW_BKG;
  while (1) { title(); newgame(loadreq); play(); }
}
